# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_auto_20170120_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archive.Individual'),
        ),
    ]
