# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0013_auto_20170224_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxpos',
            name='column',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boxpos',
            name='row',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
