# Generated by Django 2.1.5 on 2019-01-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sample_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
