# Generated by Django 2.1.5 on 2019-01-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_auto_20190118_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sample_name',
            field=models.CharField(max_length=100),
        ),
    ]
