# Generated by Django 2.1.5 on 2019-01-31 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_auto_20190130_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='active',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='sample',
            name='archived',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='sample',
            name='deactivated_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='deactivated_type',
            field=models.CharField(blank=True, choices=[('processing', 'processing'), ('used', 'used'), ('sent_out', 'sent_out'), ('disposed', 'disposed')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='received',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='sample',
            name='received_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='date_collected',
            field=models.DateField(null=True),
        ),
    ]
