# Generated by Django 2.1.5 on 2019-07-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0012_auto_20190716_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='created',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
