# Generated by Django 2.1.5 on 2019-07-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0013_auto_20190716_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sample_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
