# Generated by Django 2.1.5 on 2019-07-31 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0019_sample_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='name',
        ),
    ]
