# Generated by Django 2.1.5 on 2019-07-31 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0021_sample_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='sample_name',
        ),
    ]
