# Generated by Django 2.1.5 on 2019-04-23 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sandlot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
        migrations.RemoveField(
            model_name='person',
            name='country',
        ),
    ]
