# Generated by Django 2.1.5 on 2019-02-06 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0006_auto_20190205_1302'),
        ('sequence', '0002_auto_20190206_1712'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WUSubmission',
            new_name='WUSSubmission',
        ),
    ]
