# Generated by Django 2.1.5 on 2019-02-07 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0009_auto_20190207_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wuspool',
            name='wus_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sequence.WUSSubmission'),
        ),
    ]
