# Generated by Django 2.1.5 on 2019-08-23 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0026_poolingamount_unique_id'),
        ('sequence', '0010_auto_20190207_1815'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WUSLaneResult',
            new_name='WUSResult',
        ),
    ]
