# Generated by Django 2.1.5 on 2019-08-23 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0011_auto_20190823_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wuspool',
            name='wus_name',
        ),
        migrations.AddField(
            model_name='wuspool',
            name='parent_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sequence.WUSSubmission', verbose_name='WUS Name'),
        ),
    ]
