# Generated by Django 2.1.5 on 2019-08-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0016_wuspool_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wussubmission',
            name='unique_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wussubmission',
            name='batch_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='wus name'),
        ),
    ]
