# Generated by Django 2.1.5 on 2019-09-03 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0017_auto_20190826_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wusresult',
            name='wuspool_name',
        ),
        migrations.AddField(
            model_name='wusresult',
            name='parent_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sequence.WUSPool', verbose_name='WUS Pool Name'),
        ),
    ]
