# Generated by Django 2.1.5 on 2019-09-04 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0019_auto_20190903_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wuspool',
            name='batch_id',
        ),
        migrations.RemoveField(
            model_name='wuspool',
            name='wus_pool_name',
        ),
    ]
