# Generated by Django 2.1.5 on 2019-09-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0020_auto_20190904_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wuspool',
            name='num_of_lanes',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
