# Generated by Django 2.1.5 on 2019-09-04 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0021_auto_20190904_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wusresult',
            old_name='lane_id',
            new_name='unique_id',
        ),
    ]
