# Generated by Django 2.1.5 on 2019-09-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0023_auto_20190904_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='wusresult',
            name='broad_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wusresult',
            name='read',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
