# Generated by Django 2.1.5 on 2019-02-06 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0006_auto_20190205_1302'),
        ('sequence', '0003_auto_20190206_1721'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WUSResults',
            new_name='WUSResult',
        ),
    ]
