# Generated by Django 2.1.5 on 2019-02-07 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0006_auto_20190205_1302'),
        ('sequence', '0004_auto_20190206_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='WUSPools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wuspool_name', models.CharField(blank=True, max_length=100, null=True)),
                ('num_of_lanes', models.IntegerField(blank=True, null=True)),
                ('pool_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='library.Pool')),
            ],
        ),
        migrations.RenameField(
            model_name='wussubmission',
            old_name='requested_number_of_lanes',
            new_name='num_of_pools',
        ),
        migrations.RemoveField(
            model_name='wussubmission',
            name='pool_name',
        ),
        migrations.AddField(
            model_name='wuspools',
            name='wus_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sequence.WUSSubmission'),
        ),
    ]
