# Generated by Django 2.1.5 on 2019-02-07 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0006_auto_20190205_1302'),
        ('sequence', '0005_auto_20190207_1045'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WUSResult',
            new_name='WUSLaneResult',
        ),
    ]
