# Generated by Django 2.1.5 on 2019-02-07 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0006_auto_20190201_1811'),
        ('sequence', '0006_auto_20190207_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='WUSSampleResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counts', models.IntegerField(blank=True, null=True)),
                ('complexity', models.IntegerField(blank=True, null=True)),
                ('sample_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sample.Sample')),
            ],
        ),
        migrations.RenameField(
            model_name='wuslaneresult',
            old_name='barcode_size_bp',
            new_name='lane_number',
        ),
        migrations.RemoveField(
            model_name='wuslaneresult',
            name='dual_barcode',
        ),
        migrations.RemoveField(
            model_name='wuslaneresult',
            name='illumina_chemistry_ends',
        ),
        migrations.RemoveField(
            model_name='wuslaneresult',
            name='illumina_chemistry_length',
        ),
        migrations.RemoveField(
            model_name='wuslaneresult',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='wuslaneresult',
            name='quote_number',
        ),
        migrations.RemoveField(
            model_name='wuslaneresult',
            name='requested_number_of_lanes',
        ),
        migrations.RemoveField(
            model_name='wuslaneresult',
            name='submission_date',
        ),
        migrations.RemoveField(
            model_name='wuslaneresult',
            name='submitted_by',
        ),
        migrations.AddField(
            model_name='wuslaneresult',
            name='wuspool_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sequence.WUSPools'),
        ),
    ]
