# Generated by Django 2.1.5 on 2019-02-07 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0007_auto_20190207_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wuspools',
            old_name='wuspool_name',
            new_name='wus_pool_name',
        ),
    ]
