# Generated by Django 2.1.5 on 2019-02-07 17:16

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('library', '0006_auto_20190205_1302'),
        ('sequence', '0008_auto_20190207_1209'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WUSPools',
            new_name='WUSPool',
        ),
    ]
