# Generated by Django 2.1.5 on 2019-08-23 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0029_auto_20190823_1248'),
        ('sequence', '0013_wussubmission_batch_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wuspool',
            name='pool_name',
        ),
        migrations.AddField(
            model_name='wuspool',
            name='related_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='library.Pool', verbose_name='Pool Name'),
        ),
    ]
