# Generated by Django 2.1.5 on 2019-09-03 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0029_auto_20190823_1248'),
        ('sequence', '0018_auto_20190903_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wusresult',
            name='library_name',
        ),
        migrations.AddField(
            model_name='wusresult',
            name='related_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='library.PoolingAmount', verbose_name='Library Name'),
        ),
    ]
