# Generated by Django 2.1.5 on 2019-09-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0022_auto_20190904_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wusresult',
            name='unique_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
