# Generated by Django 2.1.5 on 2019-09-04 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0024_auto_20190904_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wusresult',
            name='related_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='library.Library', verbose_name='Library Name'),
        ),
    ]
