# Generated by Django 2.1.5 on 2019-09-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0025_auto_20190904_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='wusresult',
            name='fastq_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
