# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_auto_20170103_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='family_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='relationship',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='active',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sample',
            name='cells',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='conc',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='vol',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='weight',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
