# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_auto_20170120_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='project_id',
        ),
    ]
