# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('archive', '0006_remove_individual_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
