# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_individual_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project', to_field='name'),
        ),
    ]
