# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0009_auto_20170207_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freezer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('freezer_type', models.CharField(blank=True, choices=[('-80', '-80'), ('LN2', 'LN2'), ('-20', '-20'), ('Fridge', 'Fridge')], max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='freezerpos',
            name='freezer_type',
        ),
        migrations.RemoveField(
            model_name='freezerpos',
            name='name',
        ),
        migrations.AddField(
            model_name='freezerpos',
            name='freezer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archive.Freezer'),
        ),
    ]
