# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0011_auto_20170207_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freezerpos',
            name='freezer',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='archive.Freezer'),
            preserve_default=False,
        ),
    ]
