# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0012_auto_20170223_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='columns',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='rows',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='box_type',
            field=models.CharField(blank=True, choices=[('box', 'box'), ('matrix_box', 'matrix_box'), ('plate', 'plate')], max_length=20, null=True),
        ),
    ]
