# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0014_auto_20170224_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boxpos',
            old_name='box_id',
            new_name='box',
        ),
        migrations.AlterField(
            model_name='box',
            name='columns',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='rows',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boxpos',
            name='column',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='boxpos',
            name='row',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
