# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-01-10 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0015_auto_20170224_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
