# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-01-10 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0016_sample2'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample2',
            name='alt_name1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sample2',
            name='alt_name2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sample2',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
