# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-01-10 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0017_auto_20190110_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample2',
            name='family_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sample2',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sample2',
            name='karyotype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sample2',
            name='other_genetic_info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sample2',
            name='project',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sample2',
            name='relationship',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sample2',
            name='species',
            field=models.CharField(blank=True, choices=[('Homo_sapiens', 'Homo_sapiens'), ('Mus_musculus', 'Mus_musculus')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sample2',
            name='year_of_birth',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
