# Generated by Django 2.1.5 on 2019-02-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0005_auto_20190201_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='hpo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='phenotype_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='status_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='other_genetic_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
