# Generated by Django 2.1.5 on 2019-06-20 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0006_auto_20190201_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='brood',
            new_name='litter',
        ),
    ]
