# Generated by Django 2.1.5 on 2019-07-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0008_auto_20190621_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='date_collected',
            field=models.DateField(blank=True, null=True),
        ),
    ]
