# Generated by Django 2.1.5 on 2019-07-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0016_auto_20190717_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='deactivated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
