# Generated by Django 2.1.5 on 2019-07-31 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0018_auto_20190725_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
