# Generated by Django 2.1.5 on 2019-07-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0022_remove_sample_sample_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='sample_name'),
            preserve_default=False,
        ),
    ]
