# Generated by Django 2.1.5 on 2019-09-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0023_auto_20190731_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='received',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
