# Generated by Django 2.1.5 on 2019-09-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0024_auto_20190910_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='received',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=100, null=True),
        ),
    ]
