# Generated by Django 2.1.5 on 2019-09-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0025_auto_20190910_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='active',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='stored',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=100, null=True),
        ),
    ]
